export const samplePlaces = [
    {
        id: "fine-food",
        name: "Fine Food",
        category: "food",
        description: "A convenient UTown food court with a variety of affordable meal options, suitable for students looking for a quick lunch, dinner, or takeaway between classes.",
        location: {
            latitude: 1.3040525860503667,
            longitude: 103.77355047235173,
        },
        openingHours: {
            monday: [{ open: "08:00", close: "20:30" }],
            tuesday: [{ open: "08:00", close: "20:30" }],
            wednesday: [{ open: "08:00", close: "20:30" }],
            thursday: [{ open: "08:00", close: "20:30" }],
            friday: [{ open: "08:00", close: "20:30" }],
            saturday: [{ open: "08:00", close: "20:30" }],
            sunday: [{ open: "08:00", close: "20:30" }],
        },
        tags: ["food", "utown"],
    },
    {
        id: "central-library",
        name: "Central Library",
        category: "study",
        description: "One of the main study locations in NUS, offering quiet spaces for reading, revision, and focused work. A useful option for students who prefer a library environment.",
        location: {
            latitude: 1.2965436416575085,
            longitude: 103.77316770177995,
        },
        openingHours: {
            monday: [{ open: "09:00", close: "21:00" }],
            tuesday: [{ open: "09:00", close: "21:00" }],
            wednesday: [{ open: "09:00", close: "21:00" }],
            thursday: [{ open: "09:00", close: "21:00" }],
            friday: [{ open: "09:00", close: "21:00" }],
            saturday: [{ open: "09:00", close: "21:00" }],
            sunday: [],
        },
        tags: ["study", "library"],
    },
    {
        id: "flavours",
        name: "Flavours",
        category: "food",
        description: "A popular UTown canteen located near student residences and study areas. Good for students staying around UTown who want nearby food options throughout the day.",
        location: {
            latitude: 1.304401780930515,
            longitude: 103.77298236818034,
        },
        openingHours: {
            monday: [{ open: "07:30", close: "20:30" }],
            tuesday: [{ open: "07:30", close: "20:30" }],
            wednesday: [{ open: "07:30", close: "20:30" }],
            thursday: [{ open: "07:30", close: "20:30" }],
            friday: [{ open: "07:30", close: "20:30" }],
            saturday: [{ open: "07:30", close: "20:30" }],
            sunday: [{ open: "07:30", close: "20:30" }],
        },
        tags: ["food", "canteen", "utown"],
    },
    {
        id: "the-terrace",
        name: "The Terrace",
        category: "food",
        description: "A canteen near the School of Computing, useful for SoC students who want a quick meal without walking far from COM buildings. Best suited for weekday meals.",
        location: {
            latitude: 1.2943847945750535,
            longitude: 103.77434064940101,
        },
        openingHours: {
            monday: [{ open: "08:00", close: "18:00" }],
            tuesday: [{ open: "08:00", close: "18:00" }],
            wednesday: [{ open: "08:00", close: "18:00" }],
            thursday: [{ open: "08:00", close: "18:00" }],
            friday: [{ open: "08:00", close: "18:00" }],
            saturday: [],
            sunday: [],
        },
        tags: ["food", "canteen", "SoC"],
    },
    {
        id: "the-deck",
        name: "The Deck",
        category: "food",
        description: "A canteen located near the Faculty of Arts and Social Sciences, serving as a convenient food spot for students around the Central Library and FASS area.",
        location: {
            latitude: 1.2944249181062506,
            longitude: 103.77256145141628,
        },
        openingHours: {
            monday: [{ open: "08:00", close: "18:00" }],
            tuesday: [{ open: "08:00", close: "18:00" }],
            wednesday: [{ open: "08:00", close: "18:00" }],
            thursday: [{ open: "08:00", close: "18:00" }],
            friday: [{ open: "08:00", close: "18:00" }],
            saturday: [],
            sunday: [],
        },
        tags: ["food", "canteen", "fass"],
    },
    {
        id: "techno-edge",
        name: "Techno Edge",
        category: "food",
        description: "A canteen located near the Faculty of Engineering, useful for students around Engineering who want affordable meals without travelling far.",
        location: {
            latitude: 1.297665,
            longitude: 103.771946,
        },
        openingHours: {
            monday: [{ open: "08:00", close: "18:00" }],
            tuesday: [{ open: "08:00", close: "18:00" }],
            wednesday: [{ open: "08:00", close: "18:00" }],
            thursday: [{ open: "08:00", close: "18:00" }],
            friday: [{ open: "08:00", close: "18:00" }],
            saturday: [],
            sunday: [],
        },
        tags: ["food", "canteen", "engineering"],
    },
    {
        id: "frontier",
        name: "Frontier",
        category: "food",
        description: "A food court near the Science area, convenient for students attending classes or studying around the Faculty of Science.",
        location: {
            latitude: 1.296897,
            longitude: 103.780091,
        },
        openingHours: {
            monday: [{ open: "08:00", close: "19:00" }],
            tuesday: [{ open: "08:00", close: "19:00" }],
            wednesday: [{ open: "08:00", close: "19:00" }],
            thursday: [{ open: "08:00", close: "19:00" }],
            friday: [{ open: "08:00", close: "19:00" }],
            saturday: [{ open: "08:00", close: "15:00" }],
            sunday: [],
        },
        tags: ["food", "canteen", "science"],
    },
    {
        id: "science-library",
        name: "Science Library",
        category: "study",
        description: "A library near the Faculty of Science that provides a quiet environment for focused study, revision, and research.",
        location: {
            latitude: 1.296350,
            longitude: 103.780617,
        },
        openingHours: {
            monday: [{ open: "09:00", close: "21:00" }],
            tuesday: [{ open: "09:00", close: "21:00" }],
            wednesday: [{ open: "09:00", close: "21:00" }],
            thursday: [{ open: "09:00", close: "21:00" }],
            friday: [{ open: "09:00", close: "21:00" }],
            saturday: [{ open: "10:00", close: "17:00" }],
            sunday: [],
        },
        tags: ["study", "library", "science"],
    },
    {
        id: "med-sci-library",
        name: "Medical / Science Library",
        category: "study",
        description: "A study-friendly library space near the medical and science areas, suitable for students who prefer a quieter academic environment.",
        location: {
            latitude: 1.294928,
            longitude: 103.781853,
        },
        openingHours: {
            monday: [{ open: "09:00", close: "21:00" }],
            tuesday: [{ open: "09:00", close: "21:00" }],
            wednesday: [{ open: "09:00", close: "21:00" }],
            thursday: [{ open: "09:00", close: "21:00" }],
            friday: [{ open: "09:00", close: "21:00" }],
            saturday: [{ open: "10:00", close: "17:00" }],
            sunday: [],
        },
        tags: ["study", "library", "medicine", "science"],
    },
    {
        id: "yih-study-area",
        name: "YIH Study Area",
        category: "study",
        description: "A central study space at Yusof Ishak House, useful for students who want a convenient place to work near food, services, and common campus facilities.",
        location: {
            latitude: 1.298839,
            longitude: 103.775549,
        },
        openingHours: {
            monday: [{ open: "08:00", close: "22:00" }],
            tuesday: [{ open: "08:00", close: "22:00" }],
            wednesday: [{ open: "08:00", close: "22:00" }],
            thursday: [{ open: "08:00", close: "22:00" }],
            friday: [{ open: "08:00", close: "22:00" }],
            saturday: [{ open: "09:00", close: "18:00" }],
            sunday: [{ open: "09:00", close: "18:00" }],
        },
        tags: ["study", "yih", "central"],
    },
];